### ISSUE TITLE
[UI] 게시글 레이아웃 만들기

### ISSUE THREAD

**Issue by seeeuni** [SOPT-30th-Joint-Seminar-8/Android-Client#7]
## 💡 Issue
게시글 레이아웃 만들기

## 📝 todo
- [ ] 게시글 본문 레이아웃 만들기
- [ ] 댓글 입력창 레이아웃 만들기
- [ ] 댓글 레이아웃 만들기
